# Generated by Django 4.2.28 on 2026-09-05 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0194_github_issue_link_content_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordProjectSync',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('server_id', models.CharField(max_length=64)),
                ('server_name', models.CharField(default='', max_length=255)),
                ('channel_id', models.CharField(blank=True, default='', max_length=64)),
                ('webhook_url', models.URLField(max_length=1000)),
                ('bot_token', models.CharField(blank=True, default='', max_length=255)),
                ('notify_on_create', models.BooleanField(default=True)),
                ('notify_on_update', models.BooleanField(default=True)),
                ('notify_on_complete', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Discord Project Sync',
                'verbose_name_plural': 'Discord Project Syncs',
                'db_table': 'discord_project_syncs',
                'ordering': ('-created_at',),
            },
        ),
    ]
